---
- name: install apache on all application servers
  hosts:  all
  vars:
    config_path: /etc/httpd/conf.d/nived.conf
    index_path: /var/www/html/index.html
    config_files:
      - src: httpd_files/index.html.j2
        dest: "{{ index_path }}" 
      - src: httpd_files/nived.conf.j2
        dest: "{{ config_path }}"
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: true

  tasks:
    - name: Ensure httpd and firewalld is installed
      yum: 
        name:
          - httpd 
          - firewalld
        state: latest
    - name: Ensure firewalld is running 
      service:
        name: firewalld
        state: started
        enabled: true

    - name: copy all relavent files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      loop: "{{ config_files }}"
      notify: restart httpd

    - name: Ensure http port is open
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true

