- name: delete all instances
  hosts:  localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - name: Connect to digital ocean and delete all instances
      digital_ocean:
        state: deleted
        command: droplet
        name: test-1
        unique_name: yes
        api_token: "{{ token }}"
        ssh_key_ids: 23113083
