- name: Ensure playbook creates users
  hosts: all
  vars_files:
    - list.yml
    - secret.yml
  tasks:
  - name: ensure users are present
    user:
      name: "{{ item.name }}"
      state: present
      uid: "{{ item.uid }}"
      password: "{{ passwd | password_hash('sha512') }}"
    loop: "{{ username }}"
    register: output
    when: inventory_hostname in groups['webservers']

  - debug:
      var: output
